node {
    stage('Checkout') {
        checkout scm
        sh 'git log -1 --pretty=%B'
    }

    stage('Setup Environment') {
        sh """
            python3 -m venv .venv
            .venv/bin/python -m pip install --upgrade pip
            .venv/bin/python -m pip install -r requirements.txt
        """
    }

    stage('Lint & Test') {
        sh '.venv/bin/python -m pytest tests/ || true'
    }
}