$jenkinsfile = @'
pipeline {
    agent any

    environment {
        VENV_DIR = ".venv"
        PYTHON_BIN = "${env.VENV_DIR}/bin/python"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sh 'git log -1 --pretty=%B'
            }
        }

        stage('Setup Environment') {
            steps {
                sh """
                    python3 -m venv ${VENV_DIR}
                    ${PYTHON_BIN} -m pip install --upgrade pip
                    ${PYTHON_BIN} -m pip install -r requirements.txt
                """
            }
        }

        stage('Lint & Test') {
            steps {
                sh "${PYTHON_BIN} -m pytest tests/ || true"
            }
        }
    }

    post {
        always {
            echo 'Pipeline complete.'
        }
    }
}
'@

[System.IO.File]::WriteAllText("$PWD\Jenkinsfile", $jenkinsfile)